### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by Lemmih** [rgeometry/rgeometry#1]
- [ ] Update the playground to read the `?code=...` parameter.
- [ ] Update the playground with `[cfg(feature="wasm")]`.
- [ ] Disallow undocumented functions and structures.
- [ ] Hide structure implementations.
- [ ] Create roadmap.
- [ ] Add stylesheet to documentation and prettify iframes.
