### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by lemmih** [rgeometry/rgeometry#3]
Completeness:
  - [x] Playground: load gists
  - [x] Playground: device pixel ratio
  - [ ] Melkman's convex hull implementation.
  - [x] Polygon validation: Duplicate points.
  - [ ] Line intersection check in O(n log n).
  - [ ] Document: Convex::validate
  - [ ] Document: Polygon::new
  - [ ] Document: Polygon::validate
  - [ ] Document: Polygon::centroid
  - [ ] Document: Triangle::validate
  - [ ] Document: Triangle::locate

Algorithms:
  - [ ] Closest two points.
  - [ ] Convex extremes.
  - [ ] Naive point-set diameter.

Useful for testing:
  - [ ] Random monotone polygon generation.
  - [ ] Random star-shaped polygon generation.
  - [ ] Sample point from triangle.
  - [ ] Sample point from convex.
  - [ ] Sample point from polygon.
